FROM golang:1.16-buster AS builder

# GO ENV VARS
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

# COPY SRC
WORKDIR /build
COPY ../src .

# DOWNLOAND DEPS
RUN go mod tidy
RUN go mod download

# BUILD
RUN go build -o worker main-worker.go

FROM ubuntu as prod

# Uncomment if SSL certs needed
# COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ../src/schemas ./schemas
COPY --from=builder /build/worker /

CMD ["/worker"]
