// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_time.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockTimeORM struct {
	Number uint32 `gorm:"primary_key"`
	Time   uint64
}

// TableName overrides the default tablename generated by GORM
func (BlockTimeORM) TableName() string {
	return "block_times"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockTime) ToORM(ctx context.Context) (BlockTimeORM, error) {
	to := BlockTimeORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockTimeWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.Time = m.Time
	if posthook, ok := interface{}(m).(BlockTimeWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockTimeORM) ToPB(ctx context.Context) (BlockTime, error) {
	to := BlockTime{}
	var err error
	if prehook, ok := interface{}(m).(BlockTimeWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.Time = m.Time
	if posthook, ok := interface{}(m).(BlockTimeWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockTime the arg will be the target, the caller the one being converted from

// BlockTimeBeforeToORM called before default ToORM code
type BlockTimeWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockTimeORM) error
}

// BlockTimeAfterToORM called after default ToORM code
type BlockTimeWithAfterToORM interface {
	AfterToORM(context.Context, *BlockTimeORM) error
}

// BlockTimeBeforeToPB called before default ToPB code
type BlockTimeWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockTime) error
}

// BlockTimeAfterToPB called after default ToPB code
type BlockTimeWithAfterToPB interface {
	AfterToPB(context.Context, *BlockTime) error
}

// DefaultCreateBlockTime executes a basic gorm create call
func DefaultCreateBlockTime(ctx context.Context, in *BlockTime, db *gorm1.DB) (*BlockTime, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTimeORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTimeORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockTimeORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTimeORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockTime patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockTime(ctx context.Context, patchee *BlockTime, patcher *BlockTime, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockTime, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
		if f == prefix+"Time" {
			patchee.Time = patcher.Time
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockTime executes a gorm list call
func DefaultListBlockTime(ctx context.Context, db *gorm1.DB) ([]*BlockTime, error) {
	in := BlockTime{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTimeORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockTimeORM{}, &BlockTime{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTimeORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("number")
	ormResponse := []BlockTimeORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTimeORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockTime{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockTimeORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTimeORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTimeORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockTimeORM) error
}
