// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_failed_transaction.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockFailedTransactionORM struct {
	Number          uint32 `gorm:"index:block_failed_transaction_idx_number"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (BlockFailedTransactionORM) TableName() string {
	return "block_failed_transactions"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockFailedTransaction) ToORM(ctx context.Context) (BlockFailedTransactionORM, error) {
	to := BlockFailedTransactionORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockFailedTransactionWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	if posthook, ok := interface{}(m).(BlockFailedTransactionWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockFailedTransactionORM) ToPB(ctx context.Context) (BlockFailedTransaction, error) {
	to := BlockFailedTransaction{}
	var err error
	if prehook, ok := interface{}(m).(BlockFailedTransactionWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	if posthook, ok := interface{}(m).(BlockFailedTransactionWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockFailedTransaction the arg will be the target, the caller the one being converted from

// BlockFailedTransactionBeforeToORM called before default ToORM code
type BlockFailedTransactionWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockFailedTransactionORM) error
}

// BlockFailedTransactionAfterToORM called after default ToORM code
type BlockFailedTransactionWithAfterToORM interface {
	AfterToORM(context.Context, *BlockFailedTransactionORM) error
}

// BlockFailedTransactionBeforeToPB called before default ToPB code
type BlockFailedTransactionWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockFailedTransaction) error
}

// BlockFailedTransactionAfterToPB called after default ToPB code
type BlockFailedTransactionWithAfterToPB interface {
	AfterToPB(context.Context, *BlockFailedTransaction) error
}

// DefaultCreateBlockFailedTransaction executes a basic gorm create call
func DefaultCreateBlockFailedTransaction(ctx context.Context, in *BlockFailedTransaction, db *gorm1.DB) (*BlockFailedTransaction, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockFailedTransactionORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockFailedTransactionORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockFailedTransactionORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockFailedTransactionORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockFailedTransaction patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockFailedTransaction(ctx context.Context, patchee *BlockFailedTransaction, patcher *BlockFailedTransaction, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockFailedTransaction, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockFailedTransaction executes a gorm list call
func DefaultListBlockFailedTransaction(ctx context.Context, db *gorm1.DB) ([]*BlockFailedTransaction, error) {
	in := BlockFailedTransaction{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockFailedTransactionORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockFailedTransactionORM{}, &BlockFailedTransaction{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockFailedTransactionORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []BlockFailedTransactionORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockFailedTransactionORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockFailedTransaction{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockFailedTransactionORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockFailedTransactionORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockFailedTransactionORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockFailedTransactionORM) error
}
