// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_transaction.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockTransactionORM struct {
	Amount          string
	Fee             string
	Number          uint64 `gorm:"index:block_internal_transaction_idx_number"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (BlockTransactionORM) TableName() string {
	return "block_transactions"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockTransaction) ToORM(ctx context.Context) (BlockTransactionORM, error) {
	to := BlockTransactionORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockTransactionWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	to.Amount = m.Amount
	to.Fee = m.Fee
	if posthook, ok := interface{}(m).(BlockTransactionWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockTransactionORM) ToPB(ctx context.Context) (BlockTransaction, error) {
	to := BlockTransaction{}
	var err error
	if prehook, ok := interface{}(m).(BlockTransactionWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	to.Amount = m.Amount
	to.Fee = m.Fee
	if posthook, ok := interface{}(m).(BlockTransactionWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockTransaction the arg will be the target, the caller the one being converted from

// BlockTransactionBeforeToORM called before default ToORM code
type BlockTransactionWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockTransactionORM) error
}

// BlockTransactionAfterToORM called after default ToORM code
type BlockTransactionWithAfterToORM interface {
	AfterToORM(context.Context, *BlockTransactionORM) error
}

// BlockTransactionBeforeToPB called before default ToPB code
type BlockTransactionWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockTransaction) error
}

// BlockTransactionAfterToPB called after default ToPB code
type BlockTransactionWithAfterToPB interface {
	AfterToPB(context.Context, *BlockTransaction) error
}

// DefaultCreateBlockTransaction executes a basic gorm create call
func DefaultCreateBlockTransaction(ctx context.Context, in *BlockTransaction, db *gorm1.DB) (*BlockTransaction, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTransactionORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTransactionORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockTransactionORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTransactionORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockTransaction patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockTransaction(ctx context.Context, patchee *BlockTransaction, patcher *BlockTransaction, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockTransaction, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"Amount" {
			patchee.Amount = patcher.Amount
			continue
		}
		if f == prefix+"Fee" {
			patchee.Fee = patcher.Fee
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockTransaction executes a gorm list call
func DefaultListBlockTransaction(ctx context.Context, db *gorm1.DB) ([]*BlockTransaction, error) {
	in := BlockTransaction{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTransactionORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockTransactionORM{}, &BlockTransaction{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTransactionORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []BlockTransactionORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockTransactionORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockTransaction{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockTransactionORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTransactionORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockTransactionORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockTransactionORM) error
}
