// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_internal_transaction.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockInternalTransactionORM struct {
	Amount          string
	LogIndex        uint32 `gorm:"primary_key"`
	Number          uint64 `gorm:"index:block_internal_transaction_idx_number"`
	TransactionHash string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (BlockInternalTransactionORM) TableName() string {
	return "block_internal_transactions"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockInternalTransaction) ToORM(ctx context.Context) (BlockInternalTransactionORM, error) {
	to := BlockInternalTransactionORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockInternalTransactionWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Amount = m.Amount
	if posthook, ok := interface{}(m).(BlockInternalTransactionWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockInternalTransactionORM) ToPB(ctx context.Context) (BlockInternalTransaction, error) {
	to := BlockInternalTransaction{}
	var err error
	if prehook, ok := interface{}(m).(BlockInternalTransactionWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Number = m.Number
	to.TransactionHash = m.TransactionHash
	to.LogIndex = m.LogIndex
	to.Amount = m.Amount
	if posthook, ok := interface{}(m).(BlockInternalTransactionWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockInternalTransaction the arg will be the target, the caller the one being converted from

// BlockInternalTransactionBeforeToORM called before default ToORM code
type BlockInternalTransactionWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockInternalTransactionORM) error
}

// BlockInternalTransactionAfterToORM called after default ToORM code
type BlockInternalTransactionWithAfterToORM interface {
	AfterToORM(context.Context, *BlockInternalTransactionORM) error
}

// BlockInternalTransactionBeforeToPB called before default ToPB code
type BlockInternalTransactionWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockInternalTransaction) error
}

// BlockInternalTransactionAfterToPB called after default ToPB code
type BlockInternalTransactionWithAfterToPB interface {
	AfterToPB(context.Context, *BlockInternalTransaction) error
}

// DefaultCreateBlockInternalTransaction executes a basic gorm create call
func DefaultCreateBlockInternalTransaction(ctx context.Context, in *BlockInternalTransaction, db *gorm1.DB) (*BlockInternalTransaction, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockInternalTransactionORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockInternalTransactionORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockInternalTransactionORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockInternalTransactionORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockInternalTransaction patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockInternalTransaction(ctx context.Context, patchee *BlockInternalTransaction, patcher *BlockInternalTransaction, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockInternalTransaction, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
		if f == prefix+"TransactionHash" {
			patchee.TransactionHash = patcher.TransactionHash
			continue
		}
		if f == prefix+"LogIndex" {
			patchee.LogIndex = patcher.LogIndex
			continue
		}
		if f == prefix+"Amount" {
			patchee.Amount = patcher.Amount
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockInternalTransaction executes a gorm list call
func DefaultListBlockInternalTransaction(ctx context.Context, db *gorm1.DB) ([]*BlockInternalTransaction, error) {
	in := BlockInternalTransaction{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockInternalTransactionORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockInternalTransactionORM{}, &BlockInternalTransaction{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockInternalTransactionORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("transaction_hash")
	ormResponse := []BlockInternalTransactionORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockInternalTransactionORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockInternalTransaction{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockInternalTransactionORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockInternalTransactionORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockInternalTransactionORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockInternalTransactionORM) error
}
