// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_count.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type BlockCountORM struct {
	Count  uint64
	Number uint32
	Type   string `gorm:"primary_key"`
}

// TableName overrides the default tablename generated by GORM
func (BlockCountORM) TableName() string {
	return "block_counts"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *BlockCount) ToORM(ctx context.Context) (BlockCountORM, error) {
	to := BlockCountORM{}
	var err error
	if prehook, ok := interface{}(m).(BlockCountWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.Count = m.Count
	to.Number = m.Number
	if posthook, ok := interface{}(m).(BlockCountWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BlockCountORM) ToPB(ctx context.Context) (BlockCount, error) {
	to := BlockCount{}
	var err error
	if prehook, ok := interface{}(m).(BlockCountWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Type = m.Type
	to.Count = m.Count
	to.Number = m.Number
	if posthook, ok := interface{}(m).(BlockCountWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type BlockCount the arg will be the target, the caller the one being converted from

// BlockCountBeforeToORM called before default ToORM code
type BlockCountWithBeforeToORM interface {
	BeforeToORM(context.Context, *BlockCountORM) error
}

// BlockCountAfterToORM called after default ToORM code
type BlockCountWithAfterToORM interface {
	AfterToORM(context.Context, *BlockCountORM) error
}

// BlockCountBeforeToPB called before default ToPB code
type BlockCountWithBeforeToPB interface {
	BeforeToPB(context.Context, *BlockCount) error
}

// BlockCountAfterToPB called after default ToPB code
type BlockCountWithAfterToPB interface {
	AfterToPB(context.Context, *BlockCount) error
}

// DefaultCreateBlockCount executes a basic gorm create call
func DefaultCreateBlockCount(ctx context.Context, in *BlockCount, db *gorm1.DB) (*BlockCount, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockCountORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockCountORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BlockCountORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockCountORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBlockCount patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBlockCount(ctx context.Context, patchee *BlockCount, patcher *BlockCount, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*BlockCount, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Type" {
			patchee.Type = patcher.Type
			continue
		}
		if f == prefix+"Count" {
			patchee.Count = patcher.Count
			continue
		}
		if f == prefix+"Number" {
			patchee.Number = patcher.Number
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBlockCount executes a gorm list call
func DefaultListBlockCount(ctx context.Context, db *gorm1.DB) ([]*BlockCount, error) {
	in := BlockCount{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockCountORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BlockCountORM{}, &BlockCount{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockCountORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("type")
	ormResponse := []BlockCountORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BlockCountORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*BlockCount{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BlockCountORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockCountORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BlockCountORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BlockCountORM) error
}
